### ISSUE TITLE
template stacks: Configuration and bundling functionality, with internal user

### ISSUE THREAD

**Issue by suskin** [crossplaneio/crossplane#1012]
This is a group of deliverables described at a high level in #1011, targeting mid-December.

### What problem are you facing?

For a first set of functionality to satisfy a real (internal) use-case, we want to create something by around mid-November which does something real so that we can try it out, learn from it, and make progress toward our longer-term goal for template stacks.

### How could Crossplane help solve your problem?

When this is done, we will have a template stack with the following functionality, for an internal use-case:

- [ ] A validated end-to-end author flow and consumer flow working with a first real internal use-case
- [ ] **No support** for functions
- [ ] **No support** for defaults
- [ ] The Helm templating engine will be used by the stack
- [ ] Parent/child labeling for things created by the template stack, so that we have support for making a nice UI

The work will include:

- [ ] Select an internal use-case
- [ ] Support using the helm templating engine for configuration
- [ ] Create parent and child labels for resources created by template stacks
- [ ] All of the work to plumb state through the stack manager (we're assuming the stack manager will do this work) so that it can pull down the configuration files and render them using the configuration engine and the user input.
- [ ] A lot of testing

**Comment by suskin** [comment]
I'm starting on this bundle of work while the design doc updates are in review. The most ambiguous, and therefore highest priority, parts are:

* What is the interface between the controller and the templating engine?
* What is the representation of templates within the system? And, how does it go from one representation to the other?

**Comment by suskin** [comment]
I spent a bunch of time investigating how to get the core of this functionality working, and looked at invoking the configuration engine via a go library, and via a [Kubernetes Job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/). I ended up getting the Job approach working first, as using the go library was not as straightforward as I was hoping. I'm going to keep going with the Job-style approach for now until I have a full system working with an example use-case, and then I may revisit the go library approach for calling into the configuration engine. There are many tradeoffs between a Job approach and a go library approach. Here are my notes so far on the tradeoffs for the Job approach, since that's what I ended up getting working first; I may elaborate more on them later, and I may add some tradeoffs for the go library approach as well.

### Tradeoffs of using a job
#### For
* Can use the command-line API instead of the programmatic API; command line API may provide better encapsulation
* Can use individual containers
* Do not need to worry about work queueing in the main controller process
* Can use the filesystem; don't need to do everything in memory or keep the filesystem clean
* May be easier to pass around volumes than a giant chunk of in-memory files
* Can more easily have a single "template stack controller" which watches a bunch of CRDs and spins off jobs based on the CRDs showing up

#### Against
* Permissions are now a factor
* Multiple could run concurrently, which may be confusing
* Job spinup time will now be added to the latency
* Errors may be harder to handle, since exit codes or error output may need to be parsed
* Individual created objects would be strings instead of structured objects
* Status is more confusing - do we just put in the output of the job?
* Is it even testable?

**Comment by jbw976** [comment]
My biggest concern would be around handling the output and errors of the renderer, which is now through the job.  I learned that was a clunky interface from the stack manager and its usage of jobs, it essentially gets everything from the job's stdout by reading the pod logs.  Is that what you are doing to get the output from the job that runs the renderer?

**Comment by suskin** [comment]
@jbw976 I agree; getting information back out of the job seems to be the main weak point of the job approach. But it's possible that I just don't know enough about good ways to do this in Kubernetes.

> Is that what you are doing to get the output from the job that runs the renderer?

Not exactly . . . sort of. For going from rendered stuff to applied stuff, it's using a volume to pass input into a `kubectl apply -f` container. For status, it would indeed be the output of the job container. Here's an excerpt of the job I've been working with, with some placeholders for stack-specific values:

```yaml
    spec:

      volumes:
      - name: resource-configuration
        emptyDir: {}
      - name: stack-configuration
        emptyDir: {}

      initContainers:
      - name: load-stack
        image: <STACKIMAGE>:latest
        command:
        - "cp"
        args:
        - "-r"
        - "/.registry/resources/<CONFIGUREDDIRECTORY>/."
        - "/usr/share/input/"
        volumeMounts:
        - name: stack-configuration
          mountPath: /usr/share/input
        imagePullPolicy: Never

      - name: helm
        image: crossplane/helm-engine:latest
        command:
        - "helm"
        args:
        - "template"
        - "--output-dir"
        - "/usr/share/resource-configuration"
        - "/usr/share/input"
        volumeMounts:
        - name: resource-configuration
          mountPath: /usr/share/resource-configuration
        - name: stack-configuration
          mountPath: /usr/share/input
        imagePullPolicy: Never

      containers:
      - name: kubectl
        image: crossplane/kubectl:latest
        command:
        - "kubectl"
        args:
        - "apply"
        - "-R"
        - "-f"
        - "/usr/share/resource-configuration"
        volumeMounts:
        - name: resource-configuration
          mountPath: /usr/share/resource-configuration
        imagePullPolicy: Never
```
