### ISSUE TITLE
CRDs from namespace stacks should be labeled with the namespaces they can be used in

### ISSUE THREAD

**Issue by jbw976** [crossplaneio/crossplane#1015]
### What problem are you facing?

CRDs themselves are always cluster scoped, even if their instances (CRs) are namespace scoped.  This makes it challenging to enforce a permissions and access model where users of a certain namespace are only allowed access to CRDs that were intended to be installed for their namespace.

Imagine namespace stack `foo` was installed into namespace `my-ns`.  Its CRD (definition, not instances) `bar.group.io` exists at the cluster scope but there is no metadata or information on the CRD that ties it to the namespace `my-ns` where it was intended to actually be used.

This makes it difficult for a user to ask a question like "What resources can I install in my namespace?".  They don't really know what CRDs are available to them in their namespace.

### How could Crossplane help solve your problem?

The stack manager could add metadata (e.g. a label) to CRDs that it installs that adds this extra piece of information about the namespaces the CRDs were intended for.  As the stack gets installed into more namespaces, the 1 CRD record at the cluster scope can have its label updated to include the new namespace.

In the example from above, perhaps the stack manager could add a label to the CRD that looks like:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bar.group.io
  labels:
    stacks.crossplane.io/available-in-namespaces: "my-ns"
```

This could drive higher level experiences and UI to easily answer the problem for a user about what resources they can install in their namespace.

**Comment by displague** [comment]
I am curious about the benefits of setting these labels on the CRD if the same information is available in the Stack.  

Does this merely provide an alternative to getting the information from Stack records or does CRD labeling provide a better/broader experience outside of Stack labelling and the StackManager experience as a whole?

How does this choice affect an implementation?  How do you imagine this CRD namespace label being set?

### Cluster Scoped StackInstall

I've been imagining:

```
kind: StackInstall
metadata:
  name: FooStack
spec:
  package: example/bar
  namespaces:
  - my-ns
  - your-ns
```

The StackManager could use a `namespaces` field on the StackInstall to trigger initial or updated labels on the CRD, as you described.  As the StackInstall would govern the behavior of the Stack within multiple namespaces, it would need to be Cluster scoped.  There would only be one StackInstall (for a particular Stack) per cluster.

The StackManager would create Stack records, service accounts (roles, rolebindings), and a Deployment within each namespace.  UI annotations would be common and shared using annotations on the Cluster scoped CRD.

Removing a Stack from a Namespace would be a matter of removing the Namepace from the StackInstall records.

In this way, StackInstalls would require a cluster admin to manage them.  The StackInstall contains the authoritative list on what namespaces a Stack is available within.  The Stack records in each namespace would have the same predictable name and would share a common StackInstall ownerReference.  The list of CRDs could be centrally managed (by the one StackInstall).

Opposing updates from sibling namespaced Stack records governed by a parent cluster scoped StackInstall would provide a challenge.

### Namespaced StackInstall

If the desire is to keep StackInstalls Namespaced scope, allowing workspace (namespace) admins able to manage namespaced Stacks, upon reconciling a new StackInstall, the StackManager will need to verify that a particular CRD already exists.  If the CRD exists, the StackManager will need to update the namespace labels on that CRD.

### Authority: CRD Labels or StackInstalls

In either case, do CRD labels become the authoritative source of which namespaces should have StackInstall, Stack, and controller management records? Does the StackManager need to watch the CRD record for label changes (and act on those changes to uninstall namespaced StackInstall records)? When being restarted, does the StackManager list and subscribe to all CRDs that contain certain Stack labels?

Or should the StackManager list at startup, and subsequently watch changes, on all StackInstalls (as it currently does) to determine the set of labels to apply to all StackInstall CRDs.  In this way, the StackInstall records and API events act as the authority and the CRDs act as a backing store.  

Take the following example where a Stack exists in two namespaces, but was previously installed in three namespaces:

```
apiVersion: stacks.crossplane.io/v1alpha1
kind: Stack
metadata:
  name: FooStack
  namespace: my-ns
spec:
  package: foostack
  customresourcedefinitions:
  - apiVersion: bar.group.io/v1alpha1
    kind: Foo
---
apiVersion: stacks.crossplane.io/v1alpha1
kind: Stack
metadata:
  name: BarStack
  namespace: your-ns
spec:
  package: foostackfork
  customresourcedefinitions:
  - apiVersion: bar.group.io/v1alpha1
    kind: Foo
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bar.group.io
  labels:
    stacks.crossplane.io/available-in-namespaces: "my-ns, your-ns, longgone-ns"
```

When the StackManager is bootstrapping, what does it do about CRDs with existing namespace labels when those namespaces do not contain active StackInstall records (`longgone-ns`)?  And how does the SM determine if that CRD is provided by a StackInstall within the listed namespace?

The StackManager would need to list _all_ Stacks (in _all_ namespaces) and aggregate by CRDs (because namespaced StackInstalls could produce alternate Stack names and images for the same collection of CRDs).  During this Stack walk, each CRDs namespace will need to be mapped. If the CRD annotations do not match the mapped namespaces, the CRD label will need to be updated OR StackInstalls will need to be created or deleted.  The process of listing and enumerating all CRDs in all Stacks sounds expensive but could be offset with cache.

Cluster Scoped StackInstalls avoid this problem using a single StackInstall record as the authority, but may need to give up some desirable persona privileges in the process and may suffer from the same problem of two similarly sourced Stacks being different.
