### ISSUE TITLE
Document connection secrets

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane#1143]
### What problem are you facing?

There is documentation on every field of the CRDs and this is really awesome. However, in many cases resources create a connection secret that includes the credential to use the resource such as root user credentials for `MySQLInstance` resources. But there isn't really a documentation that tells you what the keys of those secrets are or what each of them means.

### How could Crossplane help solve your problem?

Just like CRD documentation, Crossplane docs could have a section that shows the format of the connection secret and what to expect for each managed resource. Ideally, this'd be auto-generated like the CRD doc.

**Comment by iAnomaly** [comment]
Bonus points: allow `writeConnectionSecretToRef`Object to accept an optional map that can be used for customizing the keys which will be ejected into the target Secret. For example:

```
writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdspostgresql-conn
    keys:
        danm: endpoint
        muvaf: username
        negz: password
```
I could imagine users preferring the key/value of the map being reversed too. Not sure which way people prefer.
