### ISSUE TITLE
Add support for a default ResourceClass

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#151]
We should support a default resource class for a given Kind. This is a stepping stone on the path to something like #91, but can improve the overall experience immediately.

This can implemented similar to `StorageClass` in [Kubernetes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) by setting an annotation:

```
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard
  namespace: crossplane-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: mysql.rds.aws.crossplane.io
...
```

or we could make it part of the ResourceClass itself:

```
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard
  namespace: crossplane-system
default: true
provisioner: mysql.rds.aws.crossplane.io
...
```

By setting default to `true` that means if an abstract resource does not specify a classRef the default storage class will be selected for a given provisioner. There can only be a single default for a  provisioner.
