### ISSUE TITLE
Contextual Properties and Separation of Concern

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#20]
I wanted to capture some thoughts about a pattern that I think we should use in conductor. Consider the following RDS example:

```yaml
apiVersion: database.aws.conductor.io/v1alpha1
kind: RDSInstance
metadata:
  name: rdssample
spec:
  class: db.t2.small # type of the db instance
  engine: postgres # what engine to use postgres, mysql, aurora-postgresql etc.
  name: pgsql # name of the database at the provider
  password: # link to database secret
    key: rdsPassword # the key in the secret
    name: rds-secret # the name of the secret
  username: postgres # Database username
  size: 10 # size in BG
  backupretentionperiod: 10 # days to keep backup, 0 means diable
  encrypted: true # should the database be encrypted
  #iops: 1000 # number of iops
  multiaz: true # multi AZ support
  storagetype: gp2 # type of the underlying storage
```

In order for us to actually create the RDS instance we need AWS credentials, AWS region, VPC information and possibly more. One option would be to explicitly add all of these into the spec of each type, something like:

```yaml
apiVersion: database.aws.conductor.io/v1alpha1
kind: RDSInstance
metadata:
  name: rdssample
spec:
  region: us-east-1
  awsCredentialsRef: mycreds
```

this approach is too restrictive and assumes that the author of the database instance has all the information needed. Instead I believe we should identify a set of properties that we think are "contextual" and can be specified at the namespace and/or cluster level, and potentially by a another person. for example, consider a new cloud provider type:

```yaml
apiVersion: aws.conductor.io/v1alpha1
kind: Provider
metadata:
  name: my-aws
  annotations:
      conductor.io/is-default-provider: true
spec:
  region: us-east-1
  awsCredentialsRef: my-aws-secret
```

An instance of the provider can be created at the namespace or at the cluster level. When an RDS instance is created in the same namespace we can default to the default provider (marked by the `condutor.io/is-default-provider` annotation) in the same namespace or the default one in the cluster. The user can also specify the provider by name on the RDS type:

```yaml
apiVersion: database.aws.conductor.io/v1alpha1
kind: RDSInstance
metadata:
  name: rdssample
spec:
  providerRef: my-aws
```

it would also be great to show the provider selected in the status section of the instance.

This approach enables a healthy separation of concern where the creator of the RDS instance does not need to know a number of contextual properties about it. A cluster-admin could set the credentials, region, and other settings. We could have more granular RBAC policies for who has access to what.

Finally, it keeps the specs of each type more concise. The same model should apply to network isolation (VPCs etc.), and other constructs.
