### ISSUE TITLE
Incorrect value in ResourceClass parameters map results in unintelligible error

### ISSUE THREAD

**Issue by lukeweber** [crossplaneio/crossplane#207]
Error repeating continuously in crossplane pod logs:

ERROR: logging before flag.Parse: E1203 13:05:58.283536   37540 reflector.go:205] github.com/crossplaneio/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to list *v1alpha1.ResourceClass: v1alpha1.ResourceClassList.Items: []v1alpha1.ResourceClass: v1alpha1.ResourceClass.Parameters: ReadString: expects " or n, but found 2, error found in #10 byte of ...|","size":20,"subnetG|..., bigger context ...|","securityGroups":"sg-01","size":20,"subnetGroupName":"eks-db-subnets"},"providerRef|...

It's a validation error because the parameters map is defined as map[string]string and I'm passing an int. It would be much more helpful if the parsing indicated more clearly that it was failing because there was an int in the map.

Yaml to reproduce:
```yaml
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: standard-mysql-error
  namespace: crossplane-system
parameters:
  size: 20
provisioner: rdsinstance.database.aws.crossplane.io/v1alpha1
providerRef:
  name: demo-aws-provider
reclaimPolicy: Delete
```

Would be nice if we dug further into this. Why isn't CRD validation causing this to fail on create?
