### ISSUE TITLE
Standardize Abstract Resource Status Fields

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#243]
Different providers populate different status fields with different values. 

One of the examples: `Workload`
- AWS:
```
  service:
    loadBalancer:
      ingress:
      - hostname: a5b98a29af91111e891430e3ce0da877-346237466.us-east-1.elb.amazonaws.com
```
- Azure and GCP
```
  service:
    loadBalancer:
      ingress:
      - ip: 168.61.145.62
```
