### ISSUE TITLE
GCP Bucket Resource does not create bucket with provided name in spec

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#381]
* Bug Report

Input Example:
```yaml
apiVersion: storage.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: foobar
  namespace: crossplane-system
spec:
  name: foobar
```
Expected: GCP bucket with name: `foobar` is created (or failed if name is already taken)
Actual: GCP bucket with name: `55af4a9c-5b42-11e9-8631-9cb6d08bde99` is created

This issue is cased by: https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/gcp/storage/bucket.go#L172
```go
return newBucketSyncDeleter(&gcpstorage.BucketClient{BucketHandle: sc.Bucket(string(b.GetUID()))}, m.Client, b, creds.ProjectID), nil
```
Where BucketHandle is created using bucket object UID value.

Suggested fix: Consider switching form `Name` property in Spec to NameFormat as in https://github.com/crossplaneio/crossplane/blob/master/pkg/apis/azure/storage/v1alpha1/types.go#L151
