### ISSUE TITLE
Add Cloud Provider Label to KubernetesClusters resources created via ResourceClaim

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#407]
### Overview
Workload Scheduler uses `clusterSelector` to select a cluster based on Label key/value.
For example:
```yaml
apiVersion: compute.crossplane.io/v1alpha1
kind: Workload
metadata:
  name: gitlab-demo
  namespace: default
spec:
  clusterSelector:
    provider: gcp
```
For KubernetesCluster resources created via static provisioning, using:
- `gkeclusters.compute.gcp.crossplane.io`
- `aksclusters.compute.azure.crossplane.io`
- `eksclusters.compute.aws.crossplane.io`
this is not an issue since labels can be specified in the metadata section

However, for cluster resources created via dynamic provisioning, using:
`kubernetesclusters.compute.crossplane.io` (ResourceClaim), this is an issue, 
since `compute/cluster/controller-handlers` do not assign any labels during the resource provisioning. Until now, the workaround was to manually label a resulted cluster object.

### Change
Kubernetes ResourceClaim handlers should assign label with key "provider" and value matching the handler implementation, i.e. `gcp_handler.go` - `gcp`, `aws_handler.go` - `aws`, etc.
