### ISSUE TITLE
Add Resource Import Functionality

### ISSUE THREAD

**Issue by ichekrygin** [crossplaneio/crossplane#409]
### Overview
One of the key Crossplain functionality is support for provisioning and life-cycle management of the public cloud managed resources. Crossplane offers two modes of resource creation:
- Static: Resource is created using a dedicated resource type (CR)
- Dynamic: Resource is created using ResourceClaim type (CR)
In either case, crossplane takes "full lifecycle" ownership of the created resource, and based on the specified Reclaim Policy, can delete managed resource upon the clean-up,

There are, however, use cases when the user would like to represent existing resources (i.e. resources provisioned outside the Crossplane) as Crossplane Resource instances.  To achieve that, Crossplane must support resource import functionality.

### Further Consideration
In order for Crossplane to provide resource import functionality following questions need to be addressed:

#### Resource Lifecycle
Will the crossplane become a "full" owner of the managed resource lifecycle.

###### Deletion
If crossplane imports a resource, can this resource be specified with ReclaimPolicy: Delete. Initial thinking, no, it cannot, i.e. all imported resources automatically get assigned (and hopefully at some point enforced) Reclaim Policy: Retain ("cannot delete something you didn't create")

##### Update
Can crossplane perform manage resource update, i.e. changing resource state/properties with the potential impact on any/all existing downstream resource consumers?

#### Clloud Porvider compatibility
There should be a special concideration that the imported resource could be "fully" managed by the existing cloud provider (service account scopes/permissions, etc)

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane/pull/399#discussion_r276082158

Per the comment above, I'm curious about how the ability to import an existing `KubernetesCluster` might affect our design for workloads.

**Comment by ichekrygin** [comment]
I don't recall any specific details of this debate.  As for:
>  whether installing a Workload in an existing Kubernetes cluster and/or namespace is a use case we should design for.

My $0.02, yes, absolutely.

**Comment by jbw976** [comment]
@negz opened a very related issue with #497 that we've closed as a duplicate.

As brought up in that issue, importing an existing resource such as a Kubernetes cluster could even be on-premises (bare-metal) resources.

Overall, there seem to be many existing resources that once imported into Crossplane could easily be consumed by new resources in Crossplane. Examples:
* existing Kubernetes cluster is imported into Crossplane and then new workloads can be scheduled to run on it
* existing database is imported into Crossplane and then new applications can consume it

**Comment by negz** [comment]
Cross linking this to #569, which tracks the work we're doing around reclaim policies. I could imagine this "import" work could affect that design and work. I've been increasingly thinking about this as "attaching" and "detaching" external resources from management as a Crossplane managed resource.

**Comment by negz** [comment]
In #726 (inspired by a suggestion from @muvaf) I proposed a new `.spec.externalResourcePolicy` that would configure, amongst other things, the ability to import existing external resources.


I like that idea @muvaf. Perhaps we could expand on it with something like:

```yaml
spec:
  # externalResourcePolicy controls how the managed resource's lifecycle
  # relates to the lifecycle of its associated external resource.
  externalResourcePolicy:
    create: Attach  # Valid values are Attach, Create, and AttachOrCreate.
    update: Observe  # Valid values are Observe, or Update.
    delete: Detach  # Valid values are Detach or Delete.
```

This would allow:
```yaml
# The default policy. Returns an error if the named external resource already
# exists at creation time.
externalResourcePolicy:
  create: Create
  update: Update
  delete: Delete
```

```yaml
# A "read only" policy, similar to a Terraform data source. Exposes the state
# of an existing external resource via the managed resource status object.
externalResourcePolicy:
  create: Attach
  update: Observe
  delete: Detach
```

```yaml
# The ability to attach an existing external resource to Crossplane reconciliation.
externalResourcePolicy:
  create: Attach
  update: Update
  delete: Delete
```

```yaml
# The equivalent of Crossplane's current reclaim policy implementation
externalResourcePolicy:
  create: CreateOrAttach
  update: Update
  delete: Detach
```
