### ISSUE TITLE
Support multiple, priority ordered resource classes?

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#554]
### What problem are you facing?

As a cluster operator providing Crossplane to the developers deploying to my cluster, I'd like to specify the configuration parameters that are used to create or allocate resources. I can do this today using Crossplane resource classes.

As a developer consuming said Crossplane instance I may or may not have some specific configuration needs for my application. Today I can do this for a very small subset of configuration parameters (i.e. database engine version) by setting these parameters on my resource claim.

One challenge in implementing this pattern is that it can be difficult to find the "lowest common denominator" settings that exist for all possible resources that can satisfy a particular claim. The `RedisCluster` claim is one example of this - we allow the claim to specify an engine version, but in practice Microsoft Azure does not actually allow you to request a specific version of Redis. We've floated the idea of removing all parameters from resource claims, or establishing a 1:1 claim to resource relationship (i.e. an `RDSInstanceClaim` that can be fullfilled only by `RDSInstance` resources) that supported all the same parameters as their resource.

### How could Crossplane help solve your problem?

Another potential direction would be to remove all parameters from resource claims, but allow them to request a priority ordered list of resource classes that would be merged in order to satisfy a claim.

For example, assume the cluster operator provided the below class:

```yaml
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: productiondb
  namespace: crossplane-system
priority: 100
parameters:
  tier: db-custom-1-3840
  region: us-west2
  storageType: PD_SSD
  storageGB: "20"
provisioner: cloudsqlinstance.database.gcp.crossplane.io/v1alpha1
providerRef:
  name: example
  namespace: crossplane-system
reclaimPolicy: Delete
```

Now imagine a developer who mostly just wants to let the cluster operator specify how their database will be configured, but who knows they'll need up to 100GB of storage. If Crossplane supported "stacked" resource classes they could do this by creating the following additional class:

```yaml
apiVersion: core.crossplane.io/v1alpha1
kind: ResourceClass
metadata:
  name: mycoolservicedb
  namespace: mycoolteam
priority: 200
parameters:
  storageGB: "100"
provisioner: cloudsqlinstance.database.gcp.crossplane.io/v1alpha1
```

They would then reference both classes in their claim, with the higher priority taking precedence:

```yaml
apiVersion: storage.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: mycoolservicedb
  namespace: mycoolteam
spec:
  classRefs:
  - name: cloudsqlinstancemysql
    namespace: crossplane-system
  - name: mycoolservicedb
    namespace: mycoolteam
  writeConnectionSecretToRef:
    name: cloudsqlinstancemysql
```

This would be merged to the equivalent to using a single resource class with the following parameters:

```yaml
parameters:
  tier: db-custom-1-3840
  region: us-west2
  storageType: PD_SSD
  # This setting from mycoolservicedb has a higher priority, so takes precedence.
  storageGB: "100"
```

Of course another alternative would be to support only a single resource class and for the developer to simply fork the `productiondb` resource class and update it. The main disadvantage here is that the developer must now keep their forked resource class in sync with any changes to the defaults recommended by the cluster operator.
