### ISSUE TITLE
Implement updated reclaim policy strategy

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#569]
Community discussion has settled on using `reclaimPolicy` in a similar manner to how Kubernetes `PersistentVolume` `reclaimPolicy` works. This is a change from the current status of `reclaimPolicy` in Crossplane. For more information, see the [**Goals** section](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-reclaim-policy.md#goals) of the [reclaim policy one-pager](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-reclaim-policy.md).

Implementation of sentiment expressed in #550

**Comment by muvaf** [comment]
I think what corresponds to `reclaimPolicy` of PVCs in our context is the policy that is between a `Claim` and `Managed`. But the design in #550 talks more about the policy between `Managed` and `Physical Resource`. That is also an important feature for especially Bring-your-own-resource scenarios, but I think naming of `reclaimPolicy` is a bit misleading. 

See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming . They completely couple the lifecycle of physical volume and the PV. Reclaim policy only decides what to do to PV in case PVC is deleted.

**Comment by hasheddan** [comment]
You are correct. If you look further down in the referenced issue (#550) you'll see the discussion around this. It is our intent to move towards a `reclaimPolicy` in Crossplane that mirrors that of PVC's and PV's. Take a look at the [design doc](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-resource-reclaim-policy.md) that came out of the discussion in that issue. It defines the current state of `reclaimPolicy` in Crossplane and makes a proposal to change it to mirror the persistent volume strategy:

On the current differences between Crossplane and Kubernetes Persistent Volume `reclaimPolicy`:
> "The most significant difference between resources in Crossplane and persistent volumes in Kubernetes is what happens upon deletion. In Kubernetes, the `reclaimPolicy` dictates what happens to the `PersistentVolume` when a `PersistentVolumeClaim` is deleted. In Crossplane, the `reclaimPolicy` dictates what happens to the `External Resource` when a `ResourceClaim` is deleted."

Proposal for moving to a more consistent `reclaimPolicy` strategy:
> "Reclaim policies exist in Crossplane in order to provide the ability for an `External Resource` to persist outside of the lifecycle of a `ResourceClaim` to which they are bound. However, the current status of reclaim policies is flawed in that it allows for the possibility that an `External Resource` that was created by Crossplane persists after the deletion of the `Managed Resource` that represents it. This leads to an inaccurate state representation for a system that should be able to serve as the single control plane across cloud providers. Reclaim policies should more closely represent the functionality implemented in Kubernetes Persistent Volumes by tightly coupling the lifecyle of `Managed Resources` with their corresponding `External Resource`."

**Comment by muvaf** [comment]
Alright, I think I got confused on what we think the current status is and what it should be on the discussions and design doc. Thanks for clarification.

I believe the first thing we need to do about this issue is to come up with a new name and leave `reclaimPolicy` to claim<>managed as it's super confusing.

**Comment by hasheddan** [comment]
Agreed that `reclaimPolicy` should refer to claim<>managed, but I am not sure if we need a new name for the managed<>external relationship (that is currently incorrectly being referred to as `reclaimPolicy`).

If we were to follow the PV reclaim strategy, the managed<>external relationship is only a result of the `reclaimPolicy` for claim<>managed. If the `reclaimPolicy` is `Delete`, the managed and the external is deleted. If the `reclaimPolicy` is `Retain`, the managed and the external are retained (if there is desire to delete afterwards then manual reclamation must take place).

Basing this off documentation [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming).

**Comment by negz** [comment]
In #726 (inspired by a suggestion from @muvaf) I proposed a new `.spec.externalResourcePolicy` that would configure, amongst other things, the behaviour that is currently controlled by `.spec.reclaimPolicy`.


I like that idea @muvaf. Perhaps we could expand on it with something like:

```yaml
spec:
  # externalResourcePolicy controls how the managed resource's lifecycle
  # relates to the lifecycle of its associated external resource.
  externalResourcePolicy:
    create: Attach  # Valid values are Attach, Create, and AttachOrCreate.
    update: Observe  # Valid values are Observe, or Update.
    delete: Detach  # Valid values are Detach or Delete.
```

This would allow:
```yaml
# The default policy. Returns an error if the named external resource already
# exists at creation time.
externalResourcePolicy:
  create: Create
  update: Update
  delete: Delete
```

```yaml
# A "read only" policy, similar to a Terraform data source. Exposes the state
# of an existing external resource via the managed resource status object.
externalResourcePolicy:
  create: Attach
  update: Observe
  delete: Detach
```

```yaml
# The ability to attach an existing external resource to Crossplane reconciliation.
externalResourcePolicy:
  create: Attach
  update: Update
  delete: Delete
```

```yaml
# The equivalent of Crossplane's current reclaim policy implementation
externalResourcePolicy:
  create: CreateOrAttach
  update: Update
  delete: Detach
```
