### ISSUE TITLE
Inter-resource attribute references

### ISSUE THREAD

**Issue by soorena776** [crossplaneio/crossplane#707]
### What problem are you facing?

Crossplane creates and monitors external resources in third party cloud providers by using managed resource types. Users can provision an external resource by submitting a claim type which results in provisioning the corresponding managed resource, which in turn provisions the corresponding external resource.

In a lot of cases for an external resource to operate properly, there needs to be some configuration performed in the related provider. For instance in order to have an `eks` cluster created in AWS, one needs to provision and configure the required network resources like `VPC` and `Subnet` (see #616 for more information).

Although each of these interconnected resources can have their own managed resource type and be created independently, there still needs to be a represention of the entire configuration as a whole. For instance if a network configuration needs one `VPC` which has one `Subnet`, not only two managed resources need to be created, but also the inter-resource relationships need to be captured to clearly represent the configuration. Let's call a set of these sort of inter-resource relationships a *resource configuration* for brevity.

Currently resource configurations are represented by shell scripts in crossplane. (See these sample [aws] and [gcp] configurations). The general approach in these scripts is to: 
1. Provision external resources individually 
2. Honor resource dependency, by provisioning in the right order
3. Extract the required attributes, and use those attributes to provision downstream resources

There are several issues with this approach, most notably:
1. Lack of readability
1. Heuristic approach using arbitrary third-party tools instead of Kubernetes
1. Flaky behavior as code evolves and interrelationships change

### How could Crossplane help solve your problem?

To represent the resource configurations in a more readable and robust way, as a first step all external resources need to be supported to be managed by Crossplane. Then a given resource configuration can be represented in a single YAML file:
- Each external resource is represented by the corresponding managed resource type's api object
- The relationship between resources are represented by *implicit references*. Here an implicit reference means that the consuming resource refers to the required resource using its external resource attributes (rather than managed resource attributes), which hasn't been explicitly mentioned in the YAML.

For instance, resource configuration for the `VPC` example mentioned earlier will look like:

```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  namespace: crossplane-system
  name: my-vpc
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  namespace: crossplane-system
  name: my-subnet
spec:
  # this is the id of the external vpc, represented by my-vpc
  # this is an implicit reference to my-vpc resource
  vpcId: anArbitraryString0123
  ...
---
```
This approach covers tasks 1 and 3 of the scripting approach mentioned above. Resource dependency for simple configurations can be automatically achieved by continuous reconciliation. For more advanced resource dependency see #708.

There are a few things to keep in mind about implicit references:
1. The readability and cohesiveness in a resource configuration YAML is still very low. This especially becomes a problem if there were multiple managed resources of the same kind.
1. The identifying attributes of a lot of external resources are indeterministic, in that they are not known or can be specified before provisioning. Therefore a resource configuration for such resources cannot be represented by implicit references. 
1. It might be desired for an administrator to make a resource configuration use an existing external resource instead of creating a new one. For instance in the above example one could imagine that `my-vpc` already exists and could be removed from the resource configuration. In such cases an implicit reference will be necessary.

To address these contradicting scenarios, I propose the notion of *reference type* as the
  following:

  ```yaml
  ...
  spec:
    ...
    someParameter:
      # one of {external, apiObject} values
      referenceType: apiObject
      # a string of attributeName.namespacedName format (apiObject case),
      # or arbitrary (external case)
      value: attributeNAme.sampleObject.sampleNamespace
    ...
  ...
  ```
This indicates that the value for `someParameter` will be retrieved from the given attribute of the referred api object. If the `referenceType` was `external`, then the `value` would be interpreted as the actual value of the external resources's `sampleParameter` attribute. Going back to our `VPC` example, now we could re-write the resource configuration as:

 ```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  namespace: crossplane-system
  name: my-vpc
spec:
  ...
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  namespace: crossplane-system
  name: my-subnet
spec:
  # this is an explicit reference to a resource which exists in this YAML
  vpcId:
      referenceType: apiObject
      value: id.my-vpc.crossplane-system
  ...
---
```
If we would want to re-use an existing `VPC` in the above configuration, we could have:

```yaml
---
apiVersion: network.aws.crossplane.io/v1alpha1
kind: Subnet
metadata:
  namespace: crossplane-system
  name: my-subnet
spec:
  # this is an implicit reference to a resource which does not exists in this YAML
  vpcId:
      referenceType: external
      value: anArbitraryString0123
  ...
---
```
Advantages of using reference types:
1. High readability and reproducibility
1. Possibility of defining deterministic resource configurations, without depending on indeterministic external resources attributes
1. Possibility of using external resource attributes

[aws]: https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/aws-credentials.sh
[gcp]: https://github.com/crossplaneio/crossplane/blob/master/cluster/examples/gcp-credentials.sh
