### ISSUE TITLE
Crossplane should refuse to operate on existing external resources

### ISSUE THREAD

**Issue by negz** [crossplaneio/crossplane#726]
### What problem are you facing?

As more and more Crossplane managed resources support updating (in addition to creating and deleting) their external resources, we're likely to run into cases where Crossplane will "implicitly adopt" and start managing existing external resources. This will become more prevalent as more Crossplane managed resources allow configuration of their underlying external resource names per https://github.com/crossplaneio/crossplane/issues/624.

For example, assume a critical 1TB CloudSQL database named `prod` exists in a particular GCP account. Further assume Crossplane is configured to use this GCP account, and a resource claim for a 10GB CloudSQL database with external name `prod` was created. Today there is no logic that would prevent Crossplane considering the existing database to be under Crossplane management, and trying to resize it down to 10GB.

### How could Crossplane help solve your problem?

Crossplane will need to be able to distinguish external resources it created from existing external resources. This may be difficult, given that not all cloud providers and external resources support storing metadata.

Relates to #409.

**Comment by muvaf** [comment]
I think we need to support both scenarios because bring-your-own-resource is also something we want for letting people adopt to Crossplane easily. I'm thinking of `attachPolicy` field in `ResourceSpec` of the managed resource with two values; one for aborting if the resource already exists, one for taking over the resource (couldn't think of names for the values right now). Then, in the managed reconciler we could have a logic where we'd not call `Update/Delete` if the policy is set to the one that says `don't touch my resource`

**Comment by negz** [comment]
I like that idea @muvaf. Perhaps we could expand on it with something like:

```yaml
spec:
  # externalResourcePolicy controls how the managed resource's lifecycle
  # relates to the lifecycle of its associated external resource.
  externalResourcePolicy:
    create: Attach  # Valid values are Attach, Create, and AttachOrCreate.
    update: Observe  # Valid values are Observe, or Update.
    delete: Detach  # Valid values are Detach or Delete.
```

This would allow:
```yaml
# The default policy. Returns an error if the named external resource already
# exists at creation time.
externalResourcePolicy:
  create: Create
  update: Update
  delete: Delete
```

```yaml
# A "read only" policy, similar to a Terraform data source. Exposes the state
# of an existing external resource via the managed resource status object.
externalResourcePolicy:
  create: Attach
  update: Observe
  delete: Detach
```

```yaml
# The ability to attach an existing external resource to Crossplane reconciliation.
externalResourcePolicy:
  create: Attach
  update: Update
  delete: Delete
```

```yaml
# The equivalent of Crossplane's current reclaim policy implementation
externalResourcePolicy:
  create: CreateOrAttach
  update: Update
  delete: Detach
```
