### ISSUE TITLE
Use KubernetesTarget kind for scheduling KubernetesApplications

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane#859]
### What problem are you facing?

The introduction of the Kubernetes `Provider` type (as specified in #841) allows for enhanced ability to schedule resources to *any* Kubernetes cluster. This functionality should be utilized by `KubernetesApplication` types instead of the current pattern of referencing a Crossplane provisioned `KubernetesCluster` by label.

### How could Crossplane help solve your problem?

The `KubernetesApplication` resource type will need to be modified to include a
`providerRef` field so that in can be referenced by the new Kubernetes `Provider` kind.
However, this should be an optional field that is only required if there is no
`clusterRef` `matchLabels` fields defined. If there is only a `clusterRef`
`matchLabels` field and no `providerRef`, the `KubernetesApplication` [scheduler
controller] should be modified such that it finds Kubernetes `Provider` objects
with the labels (instead of the current implementation that gets
`KubernetesCluster` objects with matching labels), and schedules the
`KubernetesApplication` to them in a round-robin fashion.

If a user desires to use the `providerRef` field to provision the
`KubernetesApplication`, the workflow would look as follows: 

1. Create a Kubernetes `Provider` for target cluster (using one of scenarios
   outlined above):

```yaml
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: demo-k8s-provider
  namespace: my-infra-dev
spec:
  credentialsSecretRef:
    name: demo-cluster-creds
```

2. Create a `KubernetesApplication` that references the `Provider` in its
   `providerRef`:

```yaml
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: wordpress-demo
  namespace: mynamespace
  labels:
    app: wordpress-demo
spec:
  resourceSelector:
    matchLabels:
      app: wordpress-demo
  providerRef:
    name: demo-k8s-provider
    namespace: my-infra-dev
  resourceTemplates:
  - metadata:
      name: wordpress-demo-namespace
      labels:
        app: wordpress-demo
    spec:
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: wordpress
          labels:
            app: wordpress
  - metadata:
      name: wordpress-demo-deployment
      labels:
        app: wordpress-demo
    spec:
      secrets:
        # This must match the writeConnectionSecretToRef field
        # on the database claim; it is the name of the secret to
        # pull from the crossplane cluster, from this Application's namespace.
      - name: sql
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: wordpress
          name: wordpress
          labels:
            app: wordpress
        spec:
          selector:
            matchLabels:
              app: wordpress
          template:
            metadata:
              labels:
                app: wordpress
            spec:
              containers:
                - name: wordpress
                  image: wordpress:4.6.1-apache
                  env:
                    - name: WORDPRESS_DB_HOST
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: endpoint
                    - name: WORDPRESS_DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: username
                    - name: WORDPRESS_DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: password
                  ports:
                    - containerPort: 80
                      name: wordpress
  - metadata:
      name: wordpress-demo-service
      labels:
        app: wordpress-demo
    spec:
      template:
        apiVersion: v1
        kind: Service
        metadata:
          namespace: wordpress
          name: wordpress
          labels:
            app: wordpress
        spec:
          ports:
            - port: 80
          selector:
            app: wordpress
          type: LoadBalancer
```

[scheduler controller]: https://github.com/crossplaneio/crossplane/blob/master/pkg/controller/workload/kubernetes/scheduler/scheduler.go
