### ISSUE TITLE
Revisit the use of references to crossplane-system

### ISSUE THREAD

**Issue by bassam** [crossplaneio/crossplane#89]
We currently use a full `ObjectReference` on abstract resources to identify the `ResourceClass` to be used. For example:

```yaml
apiVersion: storage.conductor.io/v1alpha1
kind: MySQLInstance
...
spec:
  classReference:
    name: standard
    namespace: conductor-system
```

In this approach a developer would need to know the name of the class `standard` and the namespace in which conductor operator is running `conductor-system`. Once approach is simplify the classReference and just use a `className` and assume that the namespace is wherever the conductor operator is running.

```yaml
apiVersion: storage.conductor.io/v1alpha1
kind: MySQLInstance
...
spec:
  className: standard
```

This approach is closer to how `StorageClass` is identified in PVC design. Storage classes are cluster scope while `ResourceClass` is at a namespace scope.

This also opens up the whole discussion on how an application developer finds out about available resources classes. Do they `kubectl get rc -n conductor-system`? do they have access to list classes in that namespace? Can they look at the spec of the resource class or would it contain sensitive information?
